### ISSUE TITLE
CRAN/Bioconductor plans?

### ISSUE THREAD

**Issue by j-andrews7** [pwwang/plotthis#1]
Do you have any plans to toss this package and friends in CRAN or Bioconductor at any point?

It's quite nice, great job.

**Comment by pwwang** [comment]
I had a terrible experience with CRAN. I will give Bioconductor a try.

**Comment by j-andrews7** [comment]
The Bioconductor folks tend to be a bit less draconian and try to work with you to iron out any wrinkles. Your code is really in pretty good shape - I don't think they'd have many complaints, though you'd have to get the `remotes` packages in your DESCRIPTION into CRAN or Bioconductor as well.

It'd certainly gain it more exposure and make it easier to publish if you plan to do so at any point though.

**Comment by pwwang** [comment]
Sure, thanks for the suggestions!

I am still working on getting one of the dependent packages [`gglogger`](https://github.com/pwwang/gglogger) on CRAN. Without success, I can't do anything with this package. 😔

**Comment by pwwang** [comment]
It's on CRAN now.
